Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,9 +14,9 @@ jobs:
             java-version: '17'
        - name: build
          run: |
-            mvn clean package
+            mvn clean package -X
        - name: List target directory (debugging)
-         run: ls -l target/
+         run: ls -l target || echo "not found"
        - name: docker build
          run: |
             docker build -t samba1232/img1 .
